### ISSUE TITLE
Meaningless exception is thrown when accessing missing request data 

### ISSUE THREAD

**Issue by lashd** [lashd/mirage#12]
When using the mirage client to access request data for a template that has not yet been triggered an nonsensical exception is reported

```
Mirage.start.requests(300)
=>
/home/team/.rvm/gems/ruby-2.0.0-p451@accessory-shop/gems/httparty-0.13.1/lib/httparty/response.rb:66:in `method_missing': undefined method `each_pair' for #<HTTParty::Response:0x00000000ab48c0> (NoMethodError)
	from /home/team/.rvm/gems/ruby-2.0.0-p451@accessory-shop/gems/hashie-2.1.1/lib/hashie/mash.rb:152:in `deep_update'
	from /home/team/.rvm/gems/ruby-2.0.0-p451@accessory-shop/gems/hashie-2.1.1/lib/hashie/mash.rb:67:in `initialize'
	from /home/team/.rvm/gems/ruby-2.0.0-p451@accessory-shop/gems/mirage-3.0.6/lib/mirage/client/request.rb:9:in `new'
	from /home/team/.rvm/gems/ruby-2.0.0-p451@accessory-shop/gems/mirage-3.0.6/lib/mirage/client/request.rb:9:in `get'
	from /home/team/.rvm/gems/ruby-2.0.0-p451@accessory-shop/gems/mirage-3.0.6/lib/mirage/client/client.rb:41:in `requests'
```

**Comment by asehra** [comment]
This error was puzzling my team for a while.
